### ISSUE TITLE
two-way binding

### ISSUE THREAD

**Issue by valeriiSkliar** [semklim/Angular_learn#1]
https://github.com/semklim/Angular_learn/blob/f0dc6225c4034a4e5421c0c297331180f8a9325a/src/app/lesson4/user/avatar-settings/avatar-settings.component.html#L2
Рома привіт, якщо буде час напиши навіщо ти тут використовуєш **[(ngModel)]**. Що це дає у практичному плані, звідки можливо змінити значення **imgWidth** так, щоб спрацювала двостороння зв'язка. Та чи не простіше було використати **[attr.value]="imgWidth"**

**Comment by semklim** [comment]
Привіт, моя ідея була в тому, що я хотів щоб `<input type="range">` мав діапазон від 0 до 1000, але якщо js визначив, що висота чи ширина картинки не може бути більшою ніж, наприклад, 600рх, то бігунок  цього елементу зупинявся на позначці 600 і при перетягуванні бігунка в сторону збільшення він або не рухався або після переміщення повертався назад.

Нажаль це не вийшло реалізувати навіть за допомогою [(ngModel)]. Тому залишив так)
А також я оперував типом даних **```number```**, [(ngModel)] дозволив мені зробити двонаправлену прив'язку даних, [attr.value]="imgWidth" просить тип даних **```string```** .
